engines:
  duplication:
    enabled: true
    config:
      languages:
        - javascript
          mass_threshold: 60
    exclude_fingerprints:
      - 9be07fde3dd62d57148fd2624e983f53
  eslint:
    enabled: true
  csslint:
    enabled: false
ratings:
  paths:
    - lib/**
exclude_paths:
    - coverage/**/*
    - build/**/*
    - node_modules/**/*
    - tests/**/*
