engines:
  duplication:
    enabled: true
    config:
      languages:
        - javascript
          mass_threshold: 60
  eslint:
    enabled: true
  csslint:
    enabled: false
ratings:
  paths:
    - lib/**
exclude_paths:
    - coverage/**/*
    - build/**/*
    - node_modules/**/*
    - tests/**/*
